---
Extract_FP_location: /DevOps_Do_Not_Delete/FP/
Extract_IM_location: /DevOps_Do_Not_Delete/IM/
Extract_JAVASDK_location: /DevOps_Do_Not_Delete/SDK/
Extract_WAS_location: /DevOps_Do_Not_Delete/WAS9/
download_FP_url: https://maven.etb.tieto.com/artifactory/fs-pcm-misc/IBM/AppServer/WebSphere/WAS9.0/FP9/
download_IIM_url: https://maven.etb.tieto.com/artifactory/fs-pcm-misc/IBM/AppServer/WebSphere/WAS9.0/IM/{{ zip }}
download_JAVASDK_url: https://maven.etb.tieto.com/artifactory/fs-pcm-misc/IBM/AppServer/WebSphere/WAS9.0/SDK/
download_WAS_url: https://maven.etb.tieto.com/artifactory/list/fs-pcm-misc/IBM/AppServer/WebSphere/WAS9.0/WAS/
imcl: /DevOps_Do_Not_Delete/IM/tools/imcl
imcl_path: /opt/tools/IBM/InstallationManager/eclipse/tools/imcl
installationDirectory: /opt/tools/IBM/WebSphere/AppServer
installationDirectory_IIM: /opt/tools/IBM/InstallationManager
log_file: /tmp/IIM_install.log
tmp_location: /tmp/im/
zip: agent.installer.lnx.gtk.x86_64_1.8.5.zip
# defaults versions for WAS installation
WASFP09: ["9.0.0-WS-WAS-FP009.zip"]
IBMWASJAVA: ["was.repo.9000.java8_part1.zip","was.repo.9000.java8_part2.zip","was.repo.9000.java8_part2.zip"]
WAS9: ["was.repo.9000.base.zip"]